### ISSUE TITLE
episodes with periods in the title are not named correctly

### ISSUE THREAD

**Issue by g4269159** [codingotaku/Animu-Downloaderu#10]
for example
"Anime Episode 2.5"
is saved with ".5" as an extension instead of "Anime Episode 2.5.mp4" and needs to be renamed manually

**Comment by codingotaku** [comment]
Welp! and here I thought I handled all kinds of URLs :/
I see that ./Hack anime are named properly, by proper I mean I replaced them with underscores because "**Windows**".

The issue seems to affect only a few Anime, I will look into this ASAP

![confused](https://media.giphy.com/media/VmifIjYCJsxfG/giphy.gif)

**Comment by codingotaku** [comment]
I modified the file creation for time being, I'm not sure if this fixes the issue so I am not closing this bug.

**Comment by codingotaku** [comment]
Fixed in the latest release!

I am working on a new app to stream(without ads) and download anime. I will definitely include some of the suggested sites :100: 
Animu downloaderu has some technical limitations on websites that generated by JavaScript, and a few of the website blocked me out for trying to crawl :( 

AnimuDownloaderu might come back, may be someone else will fork and fix my spaghetti code..
but for now, we will have to stick with just Anime1 (Server1)
